.TH rlines 1 rlines\-1.0
.SH NAME
rlines \- Print specific number of new lines.
.SH SYNOPSIS
.B rlines
.RB [ <n> | h ]
.SH DESCRIPTION
rlines is a program to print a specific number of new lines to stdout.
.SH USAGE
.TP
.BI "<n>"
How many new lines to print
.TP
.BI " h"
Print usage
.SH EXIT STATUS
Always 0
.SH AUTHOR
.EX
Lucas Mior   <lucas.mior at tutamail.com>
.EE
